export enum LoginScreenBottomSheetTypes {
    FORGOT_PASSWORD_EMAIL = "FORGOT_PASSWORD_EMAIL",
    FORGOT_PASSWORD_VERIFICATION = "FORGOT_PASSWORD_VERIFICATION",
    FORGOT_PASSWORD_NEW_PASSWORD = "FORGOT_PASSWORD_NEW_PASSWORD",
    NONE = "NONE",
}