import { LongDistanceTestGuidenceStepsType } from "../../components/molecules/LongDistanceTestGuidence/LongDistanceStepTypes";

export const LongDistanceTestGuidenceSteps: LongDistanceTestGuidenceStepsType[] =
  [
    {
      step: 1,
      title: "Step 1",
      description:
        "If you are wearing glasses wear then before performing the test",
      image: require("../../assets/step1.png"),
    },
    {
      step: 2,
      title: "Step 2",
      description: "Stand at least 2m away from the screen",
      image: require("../../assets/step2.png"),
    },
    {
      step: 3,
      title: "Step 3",
      description:
        "Once you identified the letter pronounce the letter loud and clear before clocks ticks out",
      image: require("../../assets/step3.png"),
    },
  ];

export const ShortDistanceTestGuidenceSteps: LongDistanceTestGuidenceStepsType[] =
  [
    {
      step: 1,
      title: "Step 1",
      description:
        "If you are wearing glasses wear then before performing the test",
      image: require("../../assets/step1.png"),
    },
    {
      step: 2,
      title: "Step 2",
      description: "Stand at least 35-40cm away from the screen",
      image: require("../../assets/step2.png"),
    },
    {
      step: 3,
      title: "Step 3",
      description:
        "Once you identified the letter pronounce the letter loud and clear before clocks ticks out",
      image: require("../../assets/step3.png"),
    },
  ];

export const VisionTestLetters = [
  "E",
  "F",
  "L",
  "P",
  "T",
  "D",
  "H",
  "K",
  "R",
  "S",
  "V",
  "A",
  "B",
  "Q",
  "W",
  "X",
];

export const VisionTestNumbers = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "0",
];

export const SwiperLetterDirections = ["left", "right", "up", "down"];

export enum SwiperLetterDirectionsType {
  LEFT = "left",
  RIGHT = "right",
  UP = "up",
  DOWN = "down",
}

export const nearVisionTestParagraphs = [
  "The cat sat on the mat. It looked out the window at the birds.",
  "The sun is bright today. It makes the sky look very blue.",
  "I have a red ball. I like to play with it in the park.",
  "She has a green book. She reads it every night before bed.",
  "The dog runs fast. It chases after the ball in the yard.",
  "I see a big tree. It has many green leaves and strong branches.",
  "The moon shines at night. It lights up the dark sky.",
  "The boy eats an apple. It is sweet and juicy.",
  "The girl wears a blue dress. She twirls around in it with joy.",
  "The baby smiles at me. He has small, cute teeth.",
  "The car is red and shiny. It drives down the road quickly.",
  "I like to drink milk. It is cold and refreshing.",
  "The bird sings a song. It flies high in the sky.",
  "We walk to the store. The road is long but smooth.",
  "The flower is yellow and bright. It grows in the garden.",
  "The rain falls softly. It makes everything wet.",
  "The fish swims in the water. It has fins and a tail.",
  "The chair is made of wood. It is strong and sturdy.",
  "The clock ticks on the wall. It tells us the time.",
  "The plane flies in the sky. It goes far, far away.",
  "The cake is sweet and soft. We eat it on special days.",
  "The tree gives us shade. We sit under it to rest.",
  "The sun sets in the evening. The sky turns orange and pink.",
  "The rabbit hops in the grass. It has long ears and a fluffy tail.",
  "The wind blows the leaves. They fall gently to the ground.",
  "The river flows slowly. It is calm and peaceful.",
  "The butterfly lands on a flower. It spreads its colorful wings.",
  "The clock strikes twelve. It is time for lunch.",
  "The snow falls in winter. It covers the ground in white.",
  "The stars twinkle in the night. They shine like tiny diamonds.",
  "The horse gallops in the field. It is strong and fast.",
  "The frog jumps into the pond. It makes a small splash.",
  "The bell rings at school. It tells us when class is over.",
  "The candle burns brightly. It lights up the dark room.",
  "The farmer plants seeds in the soil. He waits for them to grow.",
  "The ice cream melts in the sun. It is cold and sweet.",
  "The boat sails on the sea. It moves with the wind.",
  "The bread is fresh and warm. We eat it with butter.",
  "The pencil writes on the paper. It leaves a dark mark.",
  "The kitten plays with a ball of yarn. It bats it around the room.",
  "The clock ticks loudly. It reminds us of the time passing.",
  "The raincoat keeps us dry. We wear it when it rains.",
  "The bike has two wheels. It is fun to ride.",
  "The cookies are in the jar. They smell so good.",
  "The sun rises in the morning. It brings light to the world.",
  "The teddy bear is soft and cuddly. It is a favorite toy.",
  "The clouds are fluffy and white. They float in the blue sky.",
  "The car stops at the red light. We wait for it to turn green.",
  "The shoes are new and shiny. They make us walk tall.",
  "The juice is cold and fruity. It tastes like oranges.",
  "The bus takes us to school. We sit by the window and look outside.",
  "The doorbell rings. We go to open the door.",
  "The bird builds a nest in the tree. It keeps its eggs safe.",
  "The snowman has a carrot nose. It wears a hat and scarf.",
  "The star shines bright in the sky. It guides us in the night.",
  "The road is long and winding. It leads to a faraway place.",
  "The kite flies high in the sky. It dances in the wind.",
  "The flower blooms in spring. It brings color to the garden.",
  "The bread bakes in the oven. It smells so good.",
  "The ocean waves crash on the shore. They make a soothing sound.",
  "The grass is green and soft. We lie on it to watch the clouds.",
  "The fish tank is full of water. The fish swim around happily.",
  "The hat is big and red. It protects us from the sun.",
  "The train moves on the tracks. It takes us to new places.",
  "The spoon stirs the soup. It helps mix all the flavors together.",
  "The monkey swings from the tree. It uses its long tail to hang on.",
  "The butterfly flutters by. It has wings of many colors.",
  "The apple tree has ripe fruit. We pick them to eat.",
  "The windmill spins in the wind. It turns round and round.",
  "The dog wags its tail. It is happy to see us.",
  "The elephant has a long trunk. It uses it to pick up food.",
  "The house is warm and cozy. It keeps us safe from the cold.",
  "The clock shows the time. It helps us know when to do things.",
  "The snowflakes fall gently. They cover the ground in white.",
  "The rainbow has many colors. It appears after the rain.",
  "The cat purrs softly. It is happy and content.",
  "The car drives on the road. It takes us where we want to go.",
  "The sun warms the earth. It makes plants grow tall.",
  "The bird sings in the tree. It has a sweet, cheerful song.",
  "The boat floats on the water. It moves with the waves.",
  "The flower smells sweet. We pick it and put it in a vase.",
  "The stars shine in the night sky. They light up the darkness.",
  "The horse trots down the path. It carries us on its back.",
  "The bike has a bell. We ring it when we ride.",
  "The cake has candles on it. We blow them out and make a wish.",
  "The river flows through the valley. It is cool and refreshing.",
  "The tree grows tall. It gives us shade in the summer.",
  "The moon is round and full. It lights up the night sky.",
  "The bird flies high in the sky. It spreads its wings wide.",
  "The fish swims in the pond. It makes ripples in the water.",
  "The dog barks loudly. It warns us of strangers.",
  "The flower blooms in the garden. It adds color to the world.",
  "The rain falls on the roof. It makes a soft, steady sound.",
  "The sun sets in the evening. It paints the sky in shades of orange.",
  "The wind blows through the trees. It makes the leaves rustle.",
  "The kitten sleeps in a basket. It looks so peaceful and warm.",
  "The book has many pages. We read it to learn new things.",
  "The cake is sweet and soft. We eat it at parties.",
  "The chair is big and comfortable. We sit in it to relax.",
];
