export enum VisionTestFlows {
  TEST_FLOW_SELECTOR = "TEST_FLOW_SELECTOR",
  TEST_INSTRUCTIONS = "TEST_INSTRUCTIONS",
  TEST_SCREEN = "TEST_SCREEN",
  TEST_RESULT = "TEST_RESULT",
}

export enum VisionTestFlowsActions {
  PERFORM_BY_MYSELF = "PERFORM_BY_MYSELF",
  PERFORM_WITH_HELP = "PERFORM_WITH_HELP",
  NONE = "NONE",
}
